# Generated by Django 6.0 on 2026-01-28 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 12, 0), verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
